export const BATTLE_BACKGROUND_ASSET_KEYS = {
  FOREST: 'FOREST',
} as const;

export const MONSTER_ASSET_KEYS = {
  IGUANIGNITE: 'IGUANIGNITE',
  CARNODUSK: 'CARNODUSK',
} as const;

export const BATTLE_ASSET_KEYS = {
  HEALTH_BAR_BACKGROUND: 'HEALTH_BAR_BACKGROUND',
} as const;

export const HEALTH_BAR_ASSET_KEYS = {
  LEFT_CAP: 'LEFT_CAP',
  RIGHT_CAP: 'RIGHT_CAP',
  MIDDLE: 'MIDDLE',
} as const;
